from schemas.schema_led1 import *
from schemas.schema_led2 import *
from schemas.schema_digit import *
from schemas.schema_humi import *
from schemas.schema_lcd import *
from schemas.schema_ledstick import *
from schemas.schema_light import *
from schemas.schema_sonic import *
from schemas.schema_temp import *
from schemas.schema_thump import *